### ISSUE TITLE
[JDT] annotation lost values when resolve binding from `Annotation` to `IAnnotationBinding`

### ISSUE THREAD

**Issue by CharlesZ-Chen** [vesperin/mix#3]
Client code:

```java
import java.io.File;

import org.eclipse.jdt.core.dom.IAnnotationBinding;
import org.eclipse.jdt.core.dom.MethodDeclaration;
import org.eclipse.jdt.core.dom.NormalAnnotation;

import com.sri.callspace.Importer;
import com.vesperin.base.Context;
import com.vesperin.base.EclipseJavaParser;
import com.vesperin.base.Source;
import com.vesperin.base.visitors.MethodDeclarationVisitor;

public class MainMix {
    public static void main(String[] args) {
        File file = new File("<put path to the test source code here>");
        Source source = Importer.from(file);
        Context context = new EclipseJavaParser().parseJava(source);
        MethodDeclarationVisitor methodDeclarationVisitor = new MethodDeclarationVisitor();
        context.accept(methodDeclarationVisitor);
        for (MethodDeclaration methodDeclaration : methodDeclarationVisitor.getMethodDeclarations()) {
            for (Object object : methodDeclaration.modifiers()) {
                if (object instanceof NormalAnnotation) {
                    NormalAnnotation annotation = (NormalAnnotation) object;
                    System.err.println(annotation);
                    System.err.println(annotation.values());
                    IAnnotationBinding iAnnotationBinding = annotation.resolveAnnotationBinding();
                    System.err.println(iAnnotationBinding.getAllMemberValuePairs().length);
                }
            }
//            IMethodBinding iMethodBinding = methodDeclaration.resolveBinding();
//            IAnnotationBinding iAnnotationBinding = iMethodBinding.getAnnotations()[0];
//            Annotation node = (Annotation) Jdt.findASTNodeDeclaration(iAnnotationBinding, context.getCompilationUnit());
        }
    }
}
```

test source code:
```java
import ontology.qual.Ontology;
import ontology.qual.OntologyValue;
import java.util.*;

public class Sort11 {

  public static @Ontology(values={ontology.qual.OntologyValue.SEQUENCE}) List<Integer> sortSet(Set<Integer> set){
     return null;
  }
}
```

Run client code, you will see the `annotation` of type `NormalAnnotation` in the for-loop has value of `SEQUENCE`. However, after resolving to `IAnnotationBinding`, the value is gone.

**Comment by hsanchez** [comment]
your code seems too complicated. After debugging, and performing some minor changes, I was able to get the type annotations.

First, I created a Source object and then added to com.vesperin.base.JavaParserTest
```java
  static final Source Onto = Source.from("Example",
    String.join("\n",
      Immutable.listOf(Arrays.asList(
        ""
        ,"import java.lang.annotation.ElementType;"
        ,"import java.lang.annotation.Retention;"
        ,"import java.lang.annotation.RetentionPolicy;"
        ,"import java.lang.annotation.Target;"
        ,""
        ,"public class Example {"
        , " @Retention(RetentionPolicy.RUNTIME)"
        , " @Target({ ElementType.TYPE_USE,"
        , " ElementType.TYPE_PARAMETER })"
        , " @interface TestingAll{"
        , "   String[] value();"
        , " }"
        , " public @TestingAll(\"1\") int exit(){"
        , "   return 1;"
        , " }"
        , "}"
        ))
          )
  );
```

Second, I added a test case to JavaParserTest

```java
  @Test public void testTypeAnnotation() throws Exception {
    final Context context = new EclipseJavaParser().parseJava(Onto);
    MethodDeclarationVisitor methodDeclarationVisitor = new MethodDeclarationVisitor();
    context.accept(methodDeclarationVisitor);

    for(MethodDeclaration each : methodDeclarationVisitor.getMethodDeclarations()){
      final MethodDefinition definition = MethodDefinition.from(each);
      System.out.println(definition);
    }
  }
```

Then, on MethodDefinition, I change the body of the following method
```java
returnClassDefinition(CompilationUnit, IMethodBinding): ClassDefinition
``` 

to 
```java
    final ClassDefinition clsDef = classDefinition(unit, methodBinding.getReturnType());
    for(IAnnotationBinding eachAnnotation : methodBinding.getReturnType().getTypeAnnotations())
    clsDef.addAnnotation(MethodDefinition.annotationDefinition(eachAnnotation));
    return clsDef;
```

As I mentioned before, the goal was to find an API that we could use to get the type annotations from the return type. That API is `methodBinding.getReturnType().getTypeAnnotations()`

After the above change, I updated the ClassDefinition 
```java
    if (annotation == null) return;
    annotations.add(annotation);

    String packageToString = packageDefinition.toString();
    String toStringAnnotation = annotations.toString().replace("[", "").replace("]", "");

    this.canonicalName = (packageToString.isEmpty()
      ? (toStringAnnotation + " ") + typeName
      : packageToString + "." + typeName
    );
```

After those changes, and then running the "Second" step, this is what I get
```java
MethodDefinition {Example#exit: Example -> Example.TestingAll(value=1) int}.
```

As you can see, the type annotation (and its value) are in the method definition. 

Having written the above example, I dont think we need an updated version of JDT.... I will go ahead and make the necessary changes to Vesperin's mix and then update Callspace.

**Comment by CharlesZ-Chen** [comment]
Hi Huascar, thanks for the code.

I've noticed in your test code, you attached the annotation `@TestAll` definition in the annotated source code. And that is why JDT can parse the annotation on `public @TestingAll(\"1\") int exit()` as type annotation on the return type.

However, in practice, we don't attach the `@Ontology` definition source code to the annotated program, and inserting `@Ontology` source code to every source file we annotated seems impractical. Instead, we do:

```
import ontology.Onotlogy;
import ontolgoy.OntologyValue;

public @Ontology(OntologyValue.xxx) int test() {}
```

The problem is, when JDT cannot see the annotation definitions, it will parse the ontology annotation in above code as declared annotation on the whole method. (as JDT doesn't know the valid target locations for these annotations, but it still need to put this annotation somewhere).

I tried to include the `@Ontology` and the enum `OntologyValue` source code in the annotated source file, and it works with your code.

However, if the source file doesn't has the  `@Ontology` source code, JDT would pasre it as a declared annotation, and I cannot get the values from the parsed `IAnnotationBinding`.

**Comment by CharlesZ-Chen** [comment]
Problem solved. The reason is I didn't attach my annotation definition class on the classpath of JDT parser. Specifically, should use `ASTParser.setEnvironment(classpath, sourcefile, encoding, includeJVMclasspath)`.

For vesperin, with the updated version, should use `JavaParserConfiguration#setClasspathEntries()`.
